---
- hosts: 172.31.31.198
  become: yes
  vars:
     myvar1: git,tree,wget,apache2
    
  tasks:
  - name: i want to display myvar1
    debug:
       msg: "{{ myvar1}}"
  - name: i want to install git
    apt:
      name: "{{item}}"
      state: absent
    loop:
      - "{{myvar1}}"
       
