---                                
- hosts: all
  become: yes
  tasks:
  - name: i want to install webserver
    apt:
      name: apache2
      state: present
  - name: i want to copy file in to ansible node
    template:
         src: template/jinza.j2
         dest: /var/www/html/index.html
